# Generated by Django 5.1.1 on 2024-11-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                (
                    "description",
                    models.CharField(db_column="tx_question", max_length=264),
                ),
            ],
            options={"db_table": "question", "managed": True,},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                (
                    "login",
                    models.CharField(db_column="tx_login", max_length=264, unique=True),
                ),
                ("password", models.CharField(db_column="nb_password", max_length=128)),
                (
                    "email",
                    models.EmailField(
                        db_column="tx_email", max_length=264, unique=True
                    ),
                ),
            ],
            options={"db_table": "user", "managed": True,},
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                (
                    "correct",
                    models.BooleanField(db_column="tx_option_correct", default=False),
                ),
                (
                    "description",
                    models.CharField(db_column="tx_option_description", max_length=264),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="nb_id_question",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.question",
                    ),
                ),
            ],
            options={"db_table": "option", "managed": True,},
        ),
        migrations.CreateModel(
            name="QuestionGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                (
                    "description",
                    models.CharField(db_column="tx_question_group", max_length=264),
                ),
                (
                    "questions_group_question",
                    models.ManyToManyField(
                        db_table="question_group_question", to="core.question"
                    ),
                ),
            ],
            options={"db_table": "question_group", "managed": True,},
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                (
                    "time_per_question",
                    models.IntegerField(db_column="nb_time_per_question"),
                ),
                (
                    "description",
                    models.CharField(db_column="tx_description", max_length=264),
                ),
                (
                    "question_group",
                    models.ForeignKey(
                        db_column="nb_id_question_group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.questiongroup",
                    ),
                ),
            ],
            options={"db_table": "match", "managed": True,},
        ),
        migrations.CreateModel(
            name="MatchUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="dt_created_at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_column="dt_modified_at"),
                ),
                ("points", models.IntegerField(db_column="nb_points", default=0)),
                (
                    "right_questions",
                    models.IntegerField(db_column="nb_right_questions", default=0),
                ),
                (
                    "wrong_questions",
                    models.IntegerField(db_column="nb_wrong_questions", default=0),
                ),
                (
                    "match",
                    models.ForeignKey(
                        db_column="nb_id_match",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="nb_id_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
            ],
            options={"db_table": "match_user", "managed": True,},
        ),
    ]
