# Generated by Django 5.1.1 on 2024-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_match_id_alter_matchuser_id_alter_option_id_and_more"),
    ]
    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),

    ]
