# Generated by Django 5.1.1 on 2024-11-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_matchuser_user_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="groups",
            field=models.ManyToManyField(
                related_name="questions", to="core.questiongroup"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                db_column="nb_id_question",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="core.question",
            ),
        ),
    ]
