# Generated by Django 5.1.1 on 2024-11-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_question_groups_alter_option_question"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="groups",),
    ]
