# Generated by Django 5.1.1 on 2024-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_question_groups"),
    ]
    operations = [
        migrations.RunSQL("""
        -- Inserindo grupo de perguntas
INSERT INTO public.question_group (id, dt_created_at, dt_modified_at, tx_question_group)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Esporte');

-- Inserindo perguntas
INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual país venceu a Copa do Mundo de 2018?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'França', 1),
(2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Croácia', 1),
(3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Brasil', 1),
(4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Alemanha', 1);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Em qual esporte Michael Phelps se destacou?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Natação', 2),
(6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Atletismo', 2),
(7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ginástica', 2),
(8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tênis', 2);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o esporte mais praticado nas comunidades ribeirinhas da região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Pesca esportiva', 3),
(10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Futebol', 3),
(11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Remo', 3),
(12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Canoagem', 3);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual clube de futebol da Região Norte é conhecido como "Papão da Curuzu"?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Paysandu', 4),
(14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Remo', 4),
(15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'São Raimundo', 4),
(16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Nacional', 4);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual cidade sediou os Jogos Escolares da Juventude em 2019 na Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Manaus', 5),
(18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Belém', 5),
(19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Branco', 5),
(20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Macapá', 5);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior estádio de futebol da Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Arena da Amazônia', 6),
(22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Mangueirão', 6),
(23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Estádio Zerão', 6),
(24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Colosso do Tapajós', 6);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual o principal evento esportivo de remo que ocorre no estado do Pará?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Regata da Escola Naval', 7),
(26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Regata de Santarém', 7),
(27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Copa Amazônica de Remo', 7),
(28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Desafio Tapajós', 7);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual estado da Região Norte é conhecido por incentivar competições de canoagem?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Amazonas', 8),
(30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rondônia', 8),
(31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pará', 8),
(32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amapá', 8);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual clube de futebol é um dos mais antigos da Região Norte, fundado em 1902?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(33, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Clube do Remo', 9),
(34, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Paysandu', 9),
(35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'São Raimundo', 9),
(36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Fast Clube', 9);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é a principal competição de futebol do estado do Pará?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Campeonato Paraense', 10),
(38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Copa Verde', 10),
(39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Taça Amazônica', 10),
(40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Brasileirão Série C', 10);

INSERT INTO public.question_group (id, dt_created_at, dt_modified_at, tx_question_group)
VALUES (2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cultura na Região Norte');

-- Perguntas e opções
INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'O Festival Folclórico de Parintins é famoso por apresentar dois bois. Quais são eles?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Caprichoso e Garantido', 11),
(42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Vermelho e Azul', 11),
(43, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tupã e Curupira', 11),
(44, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Juma e Tambaqui', 11);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o prato típico mais conhecido do Pará?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(45, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Pato no tucupi', 12),
(46, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tacacá', 12),
(47, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Maniçoba', 12),
(48, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Moqueca', 12);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o principal ritmo musical associado ao Festival de Parintins?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(49, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Toada', 13),
(50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Carimbó', 13),
(51, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Samba', 13),
(52, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Frevo', 13);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual fruta amazônica é usada para fazer a bebida tradicional chamada tacacá?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(53, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tucupi', 14),
(54, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cupuaçu', 14),
(55, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Açaí', 14),
(56, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Castanha', 14);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o nome do artesanato tradicional feito com palha de tucumã no Pará?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(57, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Trançado', 15),
(58, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cerâmica Marajoara', 15),
(59, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tecelagem', 15),
(60, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Entalhe', 15);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual dança típica da Região Norte é reconhecida como patrimônio cultural brasileiro?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(61, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Carimbó', 16),
(62, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Samba de Roda', 16),
(63, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Maracatu', 16),
(64, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Bumba Meu Boi', 16);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'O que representa o boto nas lendas amazônicas?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(65, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Um homem encantador que seduz mulheres', 17),
(66, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Um animal mágico que protege os rios', 17),
(67, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Um espírito guardião das florestas', 17),
(68, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Uma entidade que controla as chuvas', 17);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (18, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é a técnica indígena tradicional usada na culinária para produzir farinha de mandioca?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tipiti', 18),
(70, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Moagem', 18),
(71, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Defumação', 18),
(72, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pilagem', 18);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (19, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual manifestação artística é destacada em Alter do Chão, no Pará?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(73, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Festa do Sairé', 19),
(74, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Festival do Boto', 19),
(75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Círio de Nazaré', 19),
(76, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Toadas dos Bois', 19);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o principal símbolo religioso do Círio de Nazaré?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(77, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'A imagem de Nossa Senhora de Nazaré', 20),
(78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'A corda do Círio', 20),
(79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'O manto dourado', 20),
(80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Os barcos do rio', 20);

INSERT INTO public.question_group (id, dt_created_at, dt_modified_at, tx_question_group)
VALUES (3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Conhecimentos Gerais da Região Norte');

-- Perguntas e opções
INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (21, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior estado em extensão territorial da Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(81, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Amazonas', 21),
(82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pará', 21),
(83, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rondônia', 21),
(84, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amapá', 21);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (22, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o rio que passa pela cidade de Manaus?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Rio Negro', 22),
(86, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Solimões', 22),
(87, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tapajós', 22),
(88, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tocantins', 22);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (23, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o bioma predominante na Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Floresta Amazônica', 23),
(90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cerrado', 23),
(91, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pantanal', 23),
(92, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Mata Atlântica', 23);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior rio da Região Norte e um dos maiores do mundo?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(93, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Rio Amazonas', 24),
(94, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tocantins', 24),
(95, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tapajós', 24),
(96, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Madeira', 24);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (25, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual fruta amazônica é conhecida como "ouro negro"?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(97, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Açaí', 25),
(98, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cupuaçu', 25),
(99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Buriti', 25),
(100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tucumã', 25);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (26, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o principal destino turístico conhecido como a "Caribe Amazônico"?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Alter do Chão', 26),
(102, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ilha do Marajó', 26),
(103, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Monte Roraima', 26),
(104, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Presidente Figueiredo', 26);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (27, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o estado mais populoso da Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(105, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Pará', 27),
(106, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amazonas', 27),
(107, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rondônia', 27),
(108, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tocantins', 27);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (28, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual estado da Região Norte tem a menor extensão territorial?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(109, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Roraima', 28),
(110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amapá', 28),
(111, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Acre', 28),
(112, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tocantins', 28);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (29, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior arquipélago fluvial do mundo, localizado na Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(113, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Ilha do Marajó', 29),
(114, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Arquipélago das Anavilhanas', 29),
(115, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ilhas do Rio Tapajós', 29),
(116, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ilha de Tupinambarana', 29);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (30, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual cidade é considerada a "capital da castanha"?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(117, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Marabá', 30),
(118, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Macapá', 30),
(119, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Branco', 30),
(120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Porto Velho', 30);

INSERT INTO public.question_group (id, dt_created_at, dt_modified_at, tx_question_group)
VALUES (4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'História da Região Norte');

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (31, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi a principal atividade econômica na época da colonização da Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(121, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Extração de drogas do sertão', 31),
(122, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pecuária', 31),
(123, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cultivo de cacau', 31),
(124, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Extração de minérios', 31);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (32, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual evento marcou a integração do Acre ao território brasileiro?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(125, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tratado de Petrópolis', 32),
(126, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Revolta dos Cabanos', 32),
(127, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Batalha do Jenipapo', 32),
(128, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Acordo de Tordesilhas', 32);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (35, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o principal produto explorado durante o Ciclo da Borracha na Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(129, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Látex', 35),
(130, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Castanha-do-pará', 35),
(131, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Madeira', 35),
(132, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cacau', 35);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual cidade foi considerada a "Paris dos Trópicos" durante o Ciclo da Borracha?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(133, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Manaus', 36),
(134, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Belém', 36),
(135, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Macapá', 36),
(136, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Santarém', 36);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (37, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o impacto da construção da rodovia Transamazônica na década de 1970?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(137, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Conflitos fundiários e desmatamento', 37),
(138, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Aumento da industrialização na região', 37),
(139, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Criação de grandes centros urbanos', 37),
(140, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Reflorestamento de áreas degradadas', 37);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (38, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Quem foi Plácido de Castro, figura importante na história da Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(141, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Líder da Revolução Acreana', 38),
(142, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Fundador de Manaus', 38),
(143, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Explorador do Rio Amazonas', 38),
(144, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Primeiro governador do Pará', 38);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (39, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o principal objetivo da Missão Rondon na Região Norte?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(145, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Construir linhas telegráficas e integrar territórios', 39),
(146, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Explorar recursos minerais', 39),
(147, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Fundar cidades na floresta', 39),
(148, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Desenvolver agricultura de subsistência', 39);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (40, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual tratado definiu a fronteira entre o Brasil e a Guiana Francesa?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(149, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tratado de Utrecht', 40),
(150, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tratado de Madri', 40),
(151, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tratado de Petrópolis', 40),
(152, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tratado de Tordesilhas', 40);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (41, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual civilização pré-colombiana influenciou a cerâmica marajoara?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(153, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Civilização Marajoara', 41),
(154, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Civilização Inca', 41),
(155, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Civilização Maia', 41),
(156, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Civilização Asteca', 41);

INSERT INTO public.question (id, dt_created_at, dt_modified_at, tx_question)
VALUES (42, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o impacto da chegada dos colonizadores europeus na Amazônia?');

INSERT INTO public.option (id, dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(157, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Redução da população indígena devido a doenças e exploração', 42),
(158, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Industrialização da região no século XVI', 42),
(159, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Urbanização acelerada', 42),
(160, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Melhoria das condições de vida dos povos nativos', 42);


        
        """),

    ]
