# Generated by Django 5.1.1 on 2024-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_question_groups"),
    ]
    operations = [
        migrations.RunSQL("""
        -- Inserindo grupo de perguntas

-- Inserindo grupo de perguntas
INSERT INTO public.question_group (dt_created_at, dt_modified_at, tx_question_group)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Esporte');

-- Inserindo perguntas
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual país venceu a Copa do Mundo de 2018?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'França', 1),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Croácia', 1),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Brasil', 1),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Alemanha', 1);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Em qual esporte Michael Phelps se destacou?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Natação', 2),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Atletismo', 2),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ginástica', 2),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tênis', 2);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o esporte mais praticado nas comunidades ribeirinhas da região Norte?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Pesca esportiva', 3),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Futebol', 3),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Remo', 3),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Canoagem', 3);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual clube de futebol da Região Norte é conhecido como "Papão da Curuzu"?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Paysandu', 4),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Remo', 4),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'São Raimundo', 4),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Nacional', 4);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual cidade sediou os Jogos Escolares da Juventude em 2019 na Região Norte?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Manaus', 5),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Belém', 5),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Branco', 5),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Macapá', 5);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior estádio de futebol da Região Norte?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Arena da Amazônia', 6),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Mangueirão', 6),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Estádio Zerão', 6),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Colosso do Tapajós', 6);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual o principal evento esportivo de remo que ocorre no estado do Pará?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Regata da Escola Naval', 7),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Regata de Santarém', 7),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Copa Amazônica de Remo', 7),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Desafio Tapajós', 7);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual estado da Região Norte é conhecido por incentivar competições de canoagem?');

INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Amazonas', 8),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rondônia', 8),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pará', 8),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amapá', 8);

INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual clube de futebol é um dos mais antigos da Região Norte, fundado em 1902?');

-- Inserindo opções para a pergunta 9
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Clube do Remo', 9),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Paysandu', 9),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'São Raimundo', 9),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Fast Clube', 9);

-- Inserindo pergunta 10
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é a principal competição de futebol do estado do Pará?');

-- Inserindo opções para a pergunta 10
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Campeonato Paraense', 10),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Copa Verde', 10),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Taça Amazônica', 10),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Brasileirão Série C', 10);

-- Inserindo grupo de perguntas "Cultura na Região Norte"
INSERT INTO public.question_group (dt_created_at, dt_modified_at, tx_question_group)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Cultura na Região Norte');

-- Inserindo pergunta 11
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'O Festival Folclórico de Parintins é famoso por apresentar dois bois. Quais são eles?');

-- Inserindo opções para a pergunta 11
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Caprichoso e Garantido', 11),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Vermelho e Azul', 11),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tupã e Curupira', 11),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Juma e Tambaqui', 11);

-- Inserindo pergunta 12
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o prato típico mais conhecido do Pará?');

-- Inserindo opções para a pergunta 12
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Pato no tucupi', 12),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tacacá', 12),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Maniçoba', 12),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Moqueca', 12);

-- Inserindo pergunta 13
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o principal ritmo musical associado ao Festival de Parintins?');

-- Inserindo opções para a pergunta 13
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Toada', 13),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Carimbó', 13),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Samba', 13),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Frevo', 13);

-- Inserindo pergunta 14
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual fruta amazônica é usada para fazer a bebida tradicional chamada tacacá?');

-- Inserindo opções para a pergunta 14
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tucupi', 14),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cupuaçu', 14),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Açaí', 14),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Castanha', 14);

-- Inserindo pergunta 15
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o nome do artesanato tradicional feito com palha de tucumã no Pará?');

-- Inserindo opções para a pergunta 15
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Trançado', 15),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cerâmica Marajoara', 15),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tecelagem', 15),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Entalhe', 15);

-- Inserindo pergunta 16
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual dança típica da Região Norte é reconhecida como patrimônio cultural brasileiro?');

-- Inserindo opções para a pergunta 16
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Carimbó', 16),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Samba de Roda', 16),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Maracatu', 16),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Bumba Meu Boi', 16);

-- Inserindo pergunta 17
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'O que representa o boto nas lendas amazônicas?');

-- Inserindo opções para a pergunta 17
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Um homem encantador que seduz mulheres', 17),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Um animal mágico que protege os rios', 17),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Um espírito guardião das florestas', 17),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Uma entidade que controla as chuvas', 17);

-- Inserindo pergunta 18
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é a técnica indígena tradicional usada na culinária para produzir farinha de mandioca?');

-- Inserindo opções para a pergunta 18
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tipiti', 18),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Moagem', 18),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Defumação', 18),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pilagem', 18);
-- Inserindo pergunta 19
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual manifestação artística é destacada em Alter do Chão, no Pará?');

-- Inserindo opções para a pergunta 19
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Festa do Sairé', 19),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Festival do Boto', 19),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Círio de Nazaré', 19),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Toadas dos Bois', 19);

-- Inserindo pergunta 20
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o principal símbolo religioso do Círio de Nazaré?');

-- Inserindo opções para a pergunta 20
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'A imagem de Nossa Senhora de Nazaré', 20),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'A corda do Círio', 20),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'O manto dourado', 20),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Os barcos do rio', 20);

-- Inserindo grupo de perguntas "Conhecimentos Gerais da Região Norte"
INSERT INTO public.question_group (dt_created_at, dt_modified_at, tx_question_group)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Conhecimentos Gerais da Região Norte');

-- Inserindo pergunta 21
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior estado em extensão territorial da Região Norte?');

-- Inserindo opções para a pergunta 21
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Amazonas', 21),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pará', 21),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rondônia', 21),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amapá', 21);

-- Inserindo pergunta 22
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o rio que passa pela cidade de Manaus?');

-- Inserindo opções para a pergunta 22
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Rio Negro', 22),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Solimões', 22),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tapajós', 22),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tocantins', 22);

-- Inserindo pergunta 23
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o bioma predominante na Região Norte?');

-- Inserindo opções para a pergunta 23
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Floresta Amazônica', 23),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cerrado', 23),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pantanal', 23),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Mata Atlântica', 23);

-- Inserindo pergunta 24
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior rio da Região Norte e um dos maiores do mundo?');

-- Inserindo opções para a pergunta 24
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Rio Amazonas', 24),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tocantins', 24),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Tapajós', 24),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Madeira', 24);

-- Inserindo pergunta 25
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual fruta amazônica é conhecida como "ouro negro"?');

-- Inserindo opções para a pergunta 25
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Açaí', 25),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cupuaçu', 25),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Buriti', 25),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tucumã', 25);

-- Inserindo pergunta 26
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o principal destino turístico conhecido como a "Caribe Amazônico"?');

-- Inserindo opções para a pergunta 26
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Alter do Chão', 26),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ilha do Marajó', 26),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Monte Roraima', 26),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Presidente Figueiredo', 26);

-- Inserindo pergunta 27
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o estado mais populoso da Região Norte?');

-- Inserindo opções para a pergunta 27
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Pará', 27),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amazonas', 27),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rondônia', 27),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tocantins', 27);

-- Inserindo pergunta 28
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual estado da Região Norte tem a menor extensão territorial?');

-- Inserindo opções para a pergunta 28
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Roraima', 28),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Amapá', 28),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Acre', 28),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tocantins', 28);

-----------------------------------------------------------------
-- Inserindo pergunta 29
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual é o maior arquipélago fluvial do mundo, localizado na Região Norte?');

-- Inserindo opções para a pergunta 29
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Ilha do Marajó', (SELECT id FROM public.question WHERE tx_question = 'Qual é o maior arquipélago fluvial do mundo, localizado na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Arquipélago das Anavilhanas', (SELECT id FROM public.question WHERE tx_question = 'Qual é o maior arquipélago fluvial do mundo, localizado na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ilhas do Rio Tapajós', (SELECT id FROM public.question WHERE tx_question = 'Qual é o maior arquipélago fluvial do mundo, localizado na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Ilha de Tupinambarana', (SELECT id FROM public.question WHERE tx_question = 'Qual é o maior arquipélago fluvial do mundo, localizado na Região Norte?'));

-- Inserindo pergunta 30
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual cidade é considerada a "capital da castanha"?');

-- Inserindo opções para a pergunta 30
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Marabá', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade é considerada a "capital da castanha"?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Macapá', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade é considerada a "capital da castanha"?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Rio Branco', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade é considerada a "capital da castanha"?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Porto Velho', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade é considerada a "capital da castanha"?'));

-- Inserindo grupo de perguntas "História da Região Norte"
INSERT INTO public.question_group (dt_created_at, dt_modified_at, tx_question_group)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'História da Região Norte');

-- Inserindo pergunta 31
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi a principal atividade econômica na época da colonização da Região Norte?');

-- Inserindo opções para a pergunta 31
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Extração de drogas do sertão', (SELECT id FROM public.question WHERE tx_question = 'Qual foi a principal atividade econômica na época da colonização da Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Pecuária', (SELECT id FROM public.question WHERE tx_question = 'Qual foi a principal atividade econômica na época da colonização da Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cultivo de cacau', (SELECT id FROM public.question WHERE tx_question = 'Qual foi a principal atividade econômica na época da colonização da Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Extração de minérios', (SELECT id FROM public.question WHERE tx_question = 'Qual foi a principal atividade econômica na época da colonização da Região Norte?'));

-- Inserindo pergunta 32
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual evento marcou a integração do Acre ao território brasileiro?');

-- Inserindo opções para a pergunta 32
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tratado de Petrópolis', (SELECT id FROM public.question WHERE tx_question = 'Qual evento marcou a integração do Acre ao território brasileiro?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Revolta dos Cabanos', (SELECT id FROM public.question WHERE tx_question = 'Qual evento marcou a integração do Acre ao território brasileiro?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Batalha do Jenipapo', (SELECT id FROM public.question WHERE tx_question = 'Qual evento marcou a integração do Acre ao território brasileiro?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Acordo de Tordesilhas', (SELECT id FROM public.question WHERE tx_question = 'Qual evento marcou a integração do Acre ao território brasileiro?'));

-- Inserindo pergunta 35
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o principal produto explorado durante o Ciclo da Borracha na Região Norte?');

-- Inserindo opções para a pergunta 35
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Látex', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal produto explorado durante o Ciclo da Borracha na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Castanha-do-pará', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal produto explorado durante o Ciclo da Borracha na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Madeira', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal produto explorado durante o Ciclo da Borracha na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Cacau', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal produto explorado durante o Ciclo da Borracha na Região Norte?'));

-- Inserindo pergunta 36
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual cidade foi considerada a "Paris dos Trópicos" durante o Ciclo da Borracha?');

-- Inserindo opções para a pergunta 36
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Manaus', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade foi considerada a "Paris dos Trópicos" durante o Ciclo da Borracha?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Belém', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade foi considerada a "Paris dos Trópicos" durante o Ciclo da Borracha?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Macapá', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade foi considerada a "Paris dos Trópicos" durante o Ciclo da Borracha?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Santarém', (SELECT id FROM public.question WHERE tx_question = 'Qual cidade foi considerada a "Paris dos Trópicos" durante o Ciclo da Borracha?'));

-- Inserindo pergunta 37
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o impacto da construção da rodovia Transamazônica na década de 1970?');

-- Inserindo opções para a pergunta 37
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Conflitos fundiários e desmatamento', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da construção da rodovia Transamazônica na década de 1970?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Aumento da industrialização na região', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da construção da rodovia Transamazônica na década de 1970?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Criação de grandes centros urbanos', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da construção da rodovia Transamazônica na década de 1970?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Reflorestamento de áreas degradadas', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da construção da rodovia Transamazônica na década de 1970?'));

-- Inserindo pergunta 38
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Quem foi Plácido de Castro, figura importante na história da Região Norte?');

-- Inserindo opções para a pergunta 38
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Líder da Revolução Acreana', (SELECT id FROM public.question WHERE tx_question = 'Quem foi Plácido de Castro, figura importante na história da Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Fundador de Manaus', (SELECT id FROM public.question WHERE tx_question = 'Quem foi Plácido de Castro, figura importante na história da Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Explorador do Rio Amazonas', (SELECT id FROM public.question WHERE tx_question = 'Quem foi Plácido de Castro, figura importante na história da Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Primeiro governador do Pará', (SELECT id FROM public.question WHERE tx_question = 'Quem foi Plácido de Castro, figura importante na história da Região Norte?'));

-- Inserindo pergunta 39
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o principal objetivo da Missão Rondon na Região Norte?');

-- Inserindo opções para a pergunta 39
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Construir linhas telegráficas e integrar territórios', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal objetivo da Missão Rondon na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Explorar recursos minerais', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal objetivo da Missão Rondon na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Fundar cidades na floresta', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal objetivo da Missão Rondon na Região Norte?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Desenvolver agricultura de subsistência', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o principal objetivo da Missão Rondon na Região Norte?'));

-- Inserindo pergunta 40
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual tratado definiu a fronteira entre o Brasil e a Guiana Francesa?');

-- Inserindo opções para a pergunta 40
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Tratado de Utrecht', (SELECT id FROM public.question WHERE tx_question = 'Qual tratado definiu a fronteira entre o Brasil e a Guiana Francesa?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tratado de Madri', (SELECT id FROM public.question WHERE tx_question = 'Qual tratado definiu a fronteira entre o Brasil e a Guiana Francesa?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tratado de Petrópolis', (SELECT id FROM public.question WHERE tx_question = 'Qual tratado definiu a fronteira entre o Brasil e a Guiana Francesa?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Tratado de Tordesilhas', (SELECT id FROM public.question WHERE tx_question = 'Qual tratado definiu a fronteira entre o Brasil e a Guiana Francesa?'));

-- Inserindo pergunta 41
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual civilização pré-colombiana influenciou a cerâmica marajoara?');

-- Inserindo opções para a pergunta 41
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Civilização Marajoara', (SELECT id FROM public.question WHERE tx_question = 'Qual civilização pré-colombiana influenciou a cerâmica marajoara?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Civilização Inca', (SELECT id FROM public.question WHERE tx_question = 'Qual civilização pré-colombiana influenciou a cerâmica marajoara?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Civilização Maia', (SELECT id FROM public.question WHERE tx_question = 'Qual civilização pré-colombiana influenciou a cerâmica marajoara?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Civilização Asteca', (SELECT id FROM public.question WHERE tx_question = 'Qual civilização pré-colombiana influenciou a cerâmica marajoara?'));

-- Inserindo pergunta 42
INSERT INTO public.question (dt_created_at, dt_modified_at, tx_question)
VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Qual foi o impacto da chegada dos colonizadores europeus na Amazônia?');

-- Inserindo opções para a pergunta 42
INSERT INTO public.option (dt_created_at, dt_modified_at, tx_option_correct, tx_option_description, nb_id_question)
VALUES 
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, 'Redução da população indígena devido a doenças e exploração', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da chegada dos colonizadores europeus na Amazônia?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Industrialização da região no século XVI', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da chegada dos colonizadores europeus na Amazônia?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Urbanização acelerada', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da chegada dos colonizadores europeus na Amazônia?')),
(CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false, 'Melhoria das condições de vida dos povos nativos', (SELECT id FROM public.question WHERE tx_question = 'Qual foi o impacto da chegada dos colonizadores europeus na Amazônia?'));

-- cadastro question_group_question esportes
INSERT INTO public.question_group_question (questiongroup_id, question_id)
VALUES 
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(1, 7),
(1, 8),
(1, 9),
(1, 10);

-- cadastro question_group_question cultura região norte
INSERT INTO public.question_group_question (questiongroup_id, question_id)
VALUES 
(2, 11),
(2, 12),
(2, 13),
(2, 14),
(2, 15),
(2, 16),
(2, 17),
(2, 18),
(2, 19),
(2, 20);

-- cadastro question_group_question conhecimento gerais
INSERT INTO public.question_group_question (questiongroup_id, question_id)
VALUES 
(3, 21),
(3, 22),
(3, 23),
(3, 24),
(3, 25),
(3, 26),
(3, 27),
(3, 28),
(3, 29),
(3, 30);

-- cadastro question_group_question História da região Norte
INSERT INTO public.question_group_question (questiongroup_id, question_id)
VALUES 
(4, 31),
(4, 32),
(4, 33),
(4, 34),
(4, 35),
(4, 36),
(4, 37),
(4, 38),
(4, 39),
(4, 40);

        """),

    ]
